<?php

/**
 * Implements hook_block_info().
 */
function logos_block_info() {
  $blocks['block-logos'] = array(
    'info' => t('Logos'),
  );
  return $blocks;
}
 
/**
 * Implements hook_block_view().
 */
function logos_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'block-logos':
      $block['subject'] = t('Logos');
      $block['content'] = theme('block-logos', array('class' => _logos_contents()));
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function logos_theme() {
  return array(
    'block-logos' => array(
      'template' => 'block--logos',
      'variables' => array('form' => NULL),
      'path' => drupal_get_path('module', 'logos'),
    ),
  );
}

function _logos_contents() {
  $class = FALSE;
  
  $genres = array(
    1687 => array('black', 'norwegian-black'),
    1688 => array('brutal-death', 'death'),
    1689 => 'doom',
    1690 => 'folk',
    1693 => 'industrial',
    1694 => 'melodeath',
    1697 => 'power',
    1703 => 'thrash',
  );
  
  if (is_numeric(arg(1))) {
    $nid = arg(1);
    $sql = "SELECT g.field_genre_target_id AS genre_id ";
    $sql.= "FROM field_data_field_genre g ";
    $sql.= "WHERE g.bundle = :type AND entity_id = :nid AND delta = :delta LIMIT 1";
    
    $rs = db_query($sql, array(':type' => 'review', ':nid' => $nid, ':delta' => 0));
    foreach ($rs as $row) {
      if (isset($row->genre_id)) {
        
        $g = $genres[$row->genre_id];
        if (is_array($g)) {
          $class = $g[rand(0, 1)];
        } else {
          $class = $g;
        }
      }
    }
  }
  
  return $class;
}